//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mammothcode.AdminService.Components {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageMould {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageMould() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mammothcode.AdminService.Components.MessageMould", typeof(MessageMould).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0}区合伙人您好，系统已经为您结算{0}的{1}费用，金额为{2}！ 的本地化字符串。
        /// </summary>
        internal static string 区域代理人_结算 {
            get {
                return ResourceManager.GetString("区域代理人_结算", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尊敬的客户您好，您的{0}产品，总共{1}件，我们已经为您发货，请您在收到货之后打开微信小程序进行预约安装时间，有任何疑问请随时致电400-00-16916，感谢您的支持 ! 的本地化字符串。
        /// </summary>
        internal static string 客户_下单安装 {
            get {
                return ResourceManager.GetString("客户_下单安装", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尊敬的客户您好，您的{0}产品，总共{1}件，我们已经为您发货，请您在收到货之后打开微信小程序点击完成收货，有任何疑问请随时致电400-00-16916，感谢您的支持！ 的本地化字符串。
        /// </summary>
        internal static string 客户_下单无安装 {
            get {
                return ResourceManager.GetString("客户_下单无安装", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尊敬的客户，您的{0}产品，总共{1}件申请的售后系统已经受理，我们将安排服务人员{2}，手机号{1}来上门为您维修，请耐心等待！ 的本地化字符串。
        /// </summary>
        internal static string 客户_售后 {
            get {
                return ResourceManager.GetString("客户_售后", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尊敬的客户，您的{0}产品，总共{1}件已经为您开票，请及时查收！ 的本地化字符串。
        /// </summary>
        internal static string 客户_已开票 {
            get {
                return ResourceManager.GetString("客户_已开票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尊敬的客户，您申请的推广员资料已经未通过，未通过原因:{0} 的本地化字符串。
        /// </summary>
        internal static string 客户_推广员审核未通过 {
            get {
                return ResourceManager.GetString("客户_推广员审核未通过", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尊敬的客户，您申请的推广员资料已经审核通过！ 的本地化字符串。
        /// </summary>
        internal static string 客户_推广员审核通过 {
            get {
                return ResourceManager.GetString("客户_推广员审核通过", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尊敬的客户，您提现的{0}金额已经审核未通过，具体原因:{1} 的本地化字符串。
        /// </summary>
        internal static string 客户_提现不成功 {
            get {
                return ResourceManager.GetString("客户_提现不成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尊敬的客户，您提现的{0}金额已经审核通过，请及时查收！ 的本地化字符串。
        /// </summary>
        internal static string 客户_提现成功 {
            get {
                return ResourceManager.GetString("客户_提现成功", resourceCulture);
            }
        }
    }
}
